version: '3'

services:
  # BBDD mysql para Joomla
  joomladb:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: joomla
      MYSQL_PASSWORD: joomla
      MYSQL_DATABASE: joomla

  # Servidor web con Joomla
  joomla:
    image: joomla
    restart: always
    ports:
      - 80:80
    environment:
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_USER: joomla
      JOOMLA_DB_PASSWORD: joomla
      JOOMLA_DB_NAME: joomla