version: '3'

services:
  # BBDD mysql para Joomla
  joomladb:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: joomla
      MYSQL_PASSWORD: joomla
      MYSQL_DATABASE: joomla

  # Servidor web con Joomla
  joomla:
    image: joomla
    ports:
      - 80:80
    environment:
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_USER: joomla
      JOOMLA_DB_PASSWORD: joomla
      JOOMLA_DB_NAME: joomla
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
